### ISSUE TITLE
关于obj和project-object中hex文件差异的问题

### ISSUE THREAD

**Issue by BYzhaoran** [nayooooo/OLED-Faster#2]
尊敬的作者：
     我在摸索你的项目的时候，发现obj文件夹和project-object文件夹中hex文件存在差异，而obj文件夹中的文件能正常烧录运行，另一个即便作出修改也不行，苦于找不到前者的工程文件来探讨差异，找出问题，故来向您提问。

**Comment by nayooooo** [comment]
首先，`./Obj`文件夹是有问题的，因为工程中设置的文件输出路径为`./Project/Object`。
其次，我在学习OLED的过程中，遇到过商家商品页面上说明的OLED使用的驱动芯片与实际使用的芯片不同的情况，本例程仅用于`SSD1306`。
另外，由于我现在没有相关硬件，很抱歉无法为您解决这个问题。如果可以的话，请您将自己修改的部分进行说明，也欢迎发送您的硬件连接图片。

**Comment by BYzhaoran** [comment]
麻烦您了，同样是基于stc8h8k64u,自己修改的部分主要是单片机上对应iic的io口（如图），可能我相应的移植不够完全？同时
方便请教一下./Obj文件夹中相关文件的来历吗？
![1733156017883](https://github.com/user-attachments/assets/920655b2-fd1c-4b3e-b439-8c394d5fb991)

**Comment by nayooooo** [comment]
有修改这部分内容吗？
![屏幕截图 2024-12-03 002038](https://github.com/user-attachments/assets/6d87f02f-69f0-40e0-bf4b-957719f43a23)

**Comment by BYzhaoran** [comment]
的确是这个问题，很抱歉，作为初学者，因为这个简单的疏忽而打扰您，非常感谢！！！
![Uploading mmexport1733157623692.jpg…]()

**Comment by nayooooo** [comment]
没关系，毕竟我没有在这个项目中说明移植方法，也欢迎使用我的其它库
